#!/bin/bash
## fetch a .fasta sequence file using protein ID
## Tommaso Laurenzi 
## 10/12/2016
## this was my very first vaguely useful bash script (after hello.sh) 

local USAGE UNIPROT

USAGE="Usage: getfasta [PROT_ID]"
UNIPROT="http://www.uniprot.org/uniprot/IDhere.fasta"

if [[ ! $# -eq 1 ]]; then           # check for arguments 
  echo $USAGE

else
    curl -O "${UNIPROT/IDhere/$1}"
    cat "$1".fasta
fi
