#!/bin/bash
## fetch a .fasta sequence file using protein ID
## Tommaso Laurenzi 
## 10/12/2016
## this was my very first vaguely useful bash script (after hello.sh) 

local USAGE UNIPROT

USAGE="Usage: getfasta [PROT_ID, ]"
UNIPROT="https://www.uniprot.org/uniprot/IDhere.fasta"

if [[ ! $# -eq 1 ]]; then           # check for arguments 
  echo $USAGE
  exit 1
fi

for code in "$@"; do
  curl -O "${UNIPROT/IDhere/$code}"
  cat "$1".fasta
done

